{{- if and .Values.enabled (eq .Values.global.monitoring.type "built-in") -}}
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $key, $val := .Values.service.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  labels:
    app: {{ template "grafana.name" . }}
    chart: {{ template "grafana.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    kubernetes.io/cluster-service: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http-access-grafana
    protocol: TCP
    targetPort: 80
    port: 80
  selector:
    app: grafana
{{- end -}}
