apiVersion: v1
kind: Service
metadata:
  name: kiali
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "kiali.name" . }}
    chart: {{ template "kiali.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - name: http-kiali
    protocol: TCP
    port: 20001
  selector:
    app: kiali
---
apiVersion: v1
kind: Service
metadata:
  name: kiali-http
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "kiali.name" . }}
    chart: {{ template "kiali.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    kubernetes.io/cluster-service: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http-access-kiali
    protocol: TCP
    port: 80
  selector:
    app: kiali
