apiVersion: v1
name: rancher-istio
version: 1.4.400
appVersion: 1.4.4
description: Helm chart for all istio components
engine: gotpl
icon: https://istio.io/favicons/android-192x192.png
keywords:
- istio
- security
- sidecarInjectorWebhook
- mixer
- pilot
- galley
sources:
- http://github.com/istio/istio
tillerVersion: '>=2.7.2-0'
