{{- if and .Values.enabled (eq .Values.global.monitoring.type "built-in") -}}
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
  annotations:
    prometheus.io/scrape: 'true'
    {{- range $key, $val := .Values.service.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  labels:
    app: prometheus
    chart: {{ template "prometheus.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
  - name: prometheus
    protocol: TCP
    port: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-http
  namespace: {{ .Release.Namespace }}
  annotations:
  labels:
    app: prometheus
    chart: {{ template "prometheus.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    kubernetes.io/cluster-service: "true"
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
  - name: access-prometheus
    protocol: TCP
    port: 80
{{- end -}}
